language: node_js
node_js: "stable"

before_install:
  - stty cols 80

cache:
  directories:
    - node_modules
env:
  - SAUCE_BUILD=$TRAVIS_BUILD_NUMBER

node_js:
  - node

script:
  - if [ $TRAVIS_PULL_REQUEST = false ] | [ $TRAVIS_BRANCH = "master" ]; then
    npm run test:PR;
    fi
  - if [ $TRAVIS_PULL_REQUEST = true ]; then
    npm run test:travis;
    fi
  - npm run snapshot # Visual regression tests

notifications:
  email: false
  
