language: node_js
node_js: "stable"

before_install:
  - stty cols 80

cache:
  directories:
    - node_modules

node_js:
  - node

script:
  - npm run test
  - npm run test:chrome-saucelab
  - npm run test:firefox-saucelab
  - npm run snapshot # Visual regression tests

addons:
  sauce_connect: true

notifications:
  email: false
  
