language: node_js
node_js: "stable"

before_install:
  - stty cols 80
node_js:
  - node

cache:
  directories:
    - "node_modules"

script:
  - npm run test
  - npm run test:testcafe-chrome
  - npm run test:testcafe-firefox


notifications:
  email: false
  